# Generated by Django 5.2.17 on 2026-09-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='email_notifications',
            new_name='email_notification',
        ),
        migrations.AlterModelTable(
            name='usersettings',
            table='user_settings',
        ),
    ]
