# Generated by Django 5.2.17 on 2026-09-29 08:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50)),
                ('media_type', models.CharField(max_length=15)),
                ('media_title', models.CharField(max_length=255)),
                ('media_description', models.TextField()),
                ('media_image', models.TextField()),
                ('media_release_date', models.DateField(blank=True, null=True)),
                ('media_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('external_id', 'media_type'), name='unique_media_source')],
            },
        ),
    ]
